-- Add shop email settings

ALTER TABLE shops ADD COLUMN IF NOT EXISTS notification_email VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS sender_email VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS smtp_port INTEGER DEFAULT 587;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS smtp_user VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS smtp_pass VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS email_enabled BOOLEAN DEFAULT false;
